### ISSUE TITLE
Objects in list should have same type as list itself.

### ISSUE THREAD

**Issue by virdiignis** [providedh/ACDH_Salzburg_recipes#6]
Hi @rsouza. 
I don't know if this info did not reach you, or if you had no time to do this, but we have to address it before the workshops.

We need the _object_s in _objectList_s to have the same _type_ attribute as _div_ theire in. So Zuataten should be converted to ingredient. This way we'll be able to index those new entities in ElasticSearch under correct names. Thanks!

**Comment by rsouza** [comment]
Hi @virdiignis 
I apologize for not getting back sooner, as i was traveling abroad. Thanks for the reminder, i think i have everything corrected now. I am just commiting the new files. Could you please check?
Thanks and all the best.

**Comment by virdiignis** [comment]
It looks OK now. Thanks!
